<a href="https://colab.research.google.com/github/h708isgood/1091030/blob/1091031/10910314.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf
print(tf.__version__)
x=tf.random.normal([2,784])
w1=tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1=tf.Variable( tf.zeros([256]) ) #b1 
o1=tf.matmul(x,w1)+b1 # x@W+b  x:784, W:784x256 ==> 256, 
o1=tf.nn.relu(o1) #sigma, relu= activive function 



2.3.0


<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[1.0039182 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 5.0832424 ,
        0.        , 0.        , 0.        , 1.0104046 , 0.5942619 ,
        1.7046399 , 0.48471582, 0.5691321 , 6.3141723 , 0.        ,
        0.        , 0.        , 1.5918577 , 0.89360017, 0.        ,
        0.6856458 , 0.        , 2.8572807 , 3.8314934 , 1.6748695 ,
        2.5921683 , 1.4408305 , 0.        , 3.6659994 , 0.        ,
        0.725628  , 0.        , 0.        , 0.3739916 , 0.30587143,
        0.        , 0.        , 3.540146  , 0.47153056, 0.        ,
        2.4910936 , 0.        , 0.        , 0.21138108, 0.4947152 ,
        0.95300853, 0.        , 2.4345543 , 0.        , 2.3441982 ,
        0.9092989 , 2.356804  , 0.9534665 , 2.9687493 , 2.8297138 ,
        0.        , 0.19432378, 0.7385646 , 0.5640757 , 0.        ,
        0.07136536, 0.92631793, 0.        , 2.0060444 , 0.        

In [21]:
x=tf.random.normal( [4, 28*28] )
from tensorflow.keras import layers

#等於呼叫Dense的建構子__init() 得到物件 fc 
#此層有512個類神經元
fc=layers.Dense(512, activation=tf.nn.relu)
h1=fc(x)  #透過__call__,將fc當function使用, 呼叫__call__(x) 
 


<tf.Variable 'dense_7/kernel:0' shape=(784, 512) dtype=float32, numpy=
array([[ 0.06537063,  0.02199212, -0.05140084, ..., -0.03025784,
        -0.03304747,  0.02865   ],
       [-0.0559142 , -0.06626956, -0.00219665, ..., -0.00078918,
        -0.01640657,  0.02632403],
       [-0.03014438,  0.00494186, -0.01130268, ...,  0.05122381,
        -0.03676366, -0.0583721 ],
       ...,
       [ 0.02379816, -0.00534038, -0.04202349, ..., -0.06426893,
         0.05799136, -0.0618576 ],
       [ 0.03854601, -0.00575249,  0.00533439, ...,  0.02482959,
        -0.06624817,  0.02175468],
       [-0.06294481,  0.02689507, -0.00545564, ...,  0.0266091 ,
         0.04838867, -0.00516881]], dtype=float32)>

In [33]:
x=tf.random.normal( [4, 28*28] )
from tensorflow.keras import layers

#等於呼叫Dense的建構子__init() 得到物件 fc 
#此層有512個類神經元
f1=layers.Dense(512, activation=tf.nn.relu)
f2=layers.Dense(256, activation=tf.nn.relu)
f3=layers.Dense(128, activation=tf.nn.relu)
f4=layers.Dense(64, activation=tf.nn.relu)
f5=layers.Dense(32, activation=tf.nn.relu)
f6=layers.Dense(16, activation=tf.nn.relu)
f7=layers.Dense(10, activation=tf.nn.softmax)

h1=f1(x)  #透過__call__,將fc當function使用, 呼叫__call__(x) 
h2=f2(h1) 
h3=f3(h2)
h4=f4(h3)
h5=f5(h4)
h6=f6(h5)
h7=f7(h6)
f7.kernel #16x10 
f6.kernel.shape #32x16
f6.bias.shape  #[16]
f1.kernel.shape  #TensorShape([784, 512])
f2.kernel.shape  #TensorShape([512, 256])
print(f7.bias, f7.kernel)

<tf.Variable 'dense_91/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)> <tf.Variable 'dense_91/kernel:0' shape=(16, 10) dtype=float32, numpy=
array([[ 0.27550334,  0.11136037, -0.2548343 , -0.3861837 , -0.28146484,
        -0.2172595 ,  0.36828613,  0.17120332, -0.08325741,  0.06893957],
       [-0.31195974,  0.04833651,  0.34935874, -0.2848588 , -0.47653148,
         0.41868222, -0.44586366,  0.4521485 ,  0.18814576, -0.24096717],
       [-0.01618105,  0.19916898,  0.15674484,  0.06322807,  0.02852559,
        -0.1223973 , -0.2147778 , -0.47443816,  0.10372311, -0.29549062],
       [-0.01915213,  0.2961849 ,  0.44830024, -0.01793683, -0.15589076,
        -0.08154032, -0.39607784,  0.3702042 , -0.31781465, -0.3371421 ],
       [-0.37979394,  0.02859843,  0.26777238,  0.05013126, -0.3160972 ,
         0.33740163,  0.28923166,  0.24878216, -0.33352917,  0.4572752 ],
       [-0.3225282 , -0.39369637,  0.22623163, -0.4206934 ,  0.0797