<a href="https://colab.research.google.com/github/h708isgood/1091030/blob/main/try_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([  [[1,2], [4,5]], [[6,7], [8,9]]   ])
b=np.array([  [[1,2], [4,5]], [[6,7], [8,9]]  ])
print(a.shape)

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=2))

(2, 2, 2)
[[ 7  9]
 [12 14]]
[[ 5  7]
 [14 16]]
[[ 3  9]
 [13 17]]
